spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hvu
    username: postgres
    password:

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update